rules:
  bugs:
    constant-condition:
      level: error
    invalid-metadata-attribute:
      level: error
    not-equals-in-loop:
      level: error
    rule-named-if:
      level: error
    rule-shadows-builtin:
      level: error
    top-level-iteration:
      level: error
    unused-return-value:
      level: error
  custom:
    forbidden-function-call:
      forbidden-functions: []
      level: ignore
    naming-convention:
      level: ignore
  idiomatic:
    custom-has-key-construct:
      level: error
    custom-in-construct:
      level: error
    non-raw-regex-pattern:
      level: error
    use-in-operator:
      level: error
    use-some-for-output-vars:
      level: error
  imports:
    avoid-importing-input:
      level: error
    implicit-future-keywords:
      level: error
    import-shadows-import:
      level: error
    redundant-alias:
      level: error
    redundant-data-import:
      level: error
  style:
    avoid-get-and-list-prefix:
      level: error
    chained-rule-body:
      level: error
    detached-metadata:
      level: error
    external-reference:
      level: error
    file-length:
      level: error
      max-file-length: 500
    function-arg-return:
      except-functions:
        - walk
      level: error
    line-length:
      level: error
      max-line-length: 120
    no-whitespace-comment:
      level: error
    opa-fmt:
      level: error
    prefer-snake-case:
      level: error
    prefer-some-in-iteration:
      ignore-nesting-level: 2
      level: error
    todo-comment:
      level: error
    unconditional-assignment:
      level: error
    use-assignment-operator:
      level: error
  testing:
    dubious-print-sprintf:
      level: error
    file-missing-test-suffix:
      level: error
    identically-named-tests:
      level: error
    metasyntactic-variable:
      level: error
    print-or-trace-call:
      level: error
    test-outside-test-package:
      level: error
    todo-test:
      level: error
